using System;

namespace ITS.Tools.SimplePHPBlogToWordPressConverter.Entities
{

    /*
    comment_ID – unique ID of each comment, automatically generated by MySQL
    comment_post_ID – ID of the post for which the comment was made
    comment_author – name of the comment author
    comment_author_email – email of the comment author
    comment_author_url – URL of the comment author
    comment_author_IP – the IP that comment author came from
    comment_date – the data and time the comment was made
    comment_content – the actual comment
    comment_approved – whether the comment was moderated, and if yes, then how
    comment_agent – browser signature of the commenter (MSIE, Firefox, Safari, etc)
    comment_type – if it is a regular comment, or trackback , or something else
    user_id – if comment user is a registered user, you’ll have his ID in here
    */

    internal class WpCommentEntity
    {
        public long? ID { get; set; }
        public long? PostID { get; set; }
        public string Author { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public string IP { get; set; }
        public DateTime Date { get; set; }
        public DateTime DateGmt { get; set; }
        public string Content { get; set; }
        public byte Approved { get; set; }
        public int Karma { get; set; }
        public string Agent { get; set; }
        public string Type { get; set; }
        public int? UserID { get; set; }
        public int? ParentID { get; set; }
    }
}
